### ISSUE TITLE
safari debug console opens randomly when wakatime sketch plugin is installed

### ISSUE THREAD

**Issue by spnkr** [wakatime/sketch-wakatime#7] opened 2018-09-20 06:46 UTC
if I have safari open in the background, I get tons of these windows popping up randomly

<img width="1112" alt="screen shot 2018-09-20 at 2 45 56 am" src="https://user-images.githubusercontent.com/11250/45800604-69ff2f00-bc7f-11e8-9722-a19806c9ae9d.png">

**Comment by alanhamlett** [comment] 2018-09-20 06:57
Duplicate of #5

**Comment by alanhamlett** [comment] 2018-09-20 06:58
Follow these instructions to prevent Safari web inspector from opening:

https://github.com/wakatime/sketch-wakatime#turn-off-safari-web-inspector

**Closed as completed by alanhamlett** 2018-09-20 06:57 UTC
